/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => XteinkSenderPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  deviceIp: "",
  devicePort: "80",
  uploadPath: "/",
  autoCreateDir: true
};
var XteinkSenderPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "send-current-note-to-crosspoint",
      name: "Send current note to Crosspoint",
      checkCallback: (checking) => {
        const markdownView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
        if (markdownView) {
          if (!checking) {
            this.sendNoteToDevice(markdownView);
          }
          return true;
        }
        return false;
      }
    });
    this.addSettingTab(new XteinkSenderSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async sendNoteToDevice(view) {
    const ip = this.settings.deviceIp.trim();
    if (!ip) {
      new import_obsidian.Notice(
        "Please configure your device IP address in the plugin settings."
      );
      return;
    }
    const file = view.file;
    if (!file) {
      new import_obsidian.Notice("No active file found.");
      return;
    }
    const content = view.getViewData();
    const filename = file.name;
    new import_obsidian.Notice(`Sending ${filename} to Crosspoint...`);
    try {
      const boundary = "----WebKitFormBoundary" + Math.random().toString(36).substring(2);
      let body = `--${boundary}\r
`;
      body += `Content-Disposition: form-data; name="file"; filename="${filename}"\r
`;
      body += `Content-Type: text/markdown\r
\r
`;
      body += content + `\r
`;
      body += `--${boundary}--\r
`;
      const port = this.settings.devicePort.trim() || "80";
      let uploadPath = this.settings.uploadPath.trim() || "/";
      if (!uploadPath.startsWith("/")) {
        uploadPath = "/" + uploadPath;
      }
      if (this.settings.autoCreateDir && uploadPath !== "/") {
        try {
          const mkdirUrl = `http://${ip}:${port}/mkdir?path=${encodeURIComponent(uploadPath)}`;
          await (0, import_obsidian.requestUrl)({ url: mkdirUrl, method: "POST" });
        } catch (e) {
          console.error("Auto-create directory failed:", e);
        }
      }
      const url = `http://${ip}:${port}/upload?path=${encodeURIComponent(uploadPath)}`;
      const response = await (0, import_obsidian.requestUrl)({
        url,
        method: "POST",
        headers: {
          "Content-Type": `multipart/form-data; boundary=${boundary}`
        },
        body
      });
      if (response.status === 200) {
        new import_obsidian.Notice(`Successfully sent ${filename} to Crosspoint!`);
      } else {
        throw new Error(
          `Device responded with status: ${response.status}. ${response.text}`
        );
      }
    } catch (error) {
      console.error("Error sending note to Crosspoint:", error);
      new import_obsidian.Notice(`Failed to send note: ${error.message || error}`);
    }
  }
};
var XteinkSenderSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Device IP Address").setDesc(
      "The IP address of your device on the local Wi-Fi network (e.g., 192.168.1.50). Check the Crosspoint Reader Web UI settings or your router."
    ).addText(
      (text) => text.setPlaceholder("192.168.1.50").setValue(this.plugin.settings.deviceIp).onChange(async (value) => {
        this.plugin.settings.deviceIp = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Device Port").setDesc(
      "The port the Crosspoint Reader web server is running on (default is 80)."
    ).addText(
      (text) => text.setPlaceholder("80").setValue(this.plugin.settings.devicePort).onChange(async (value) => {
        this.plugin.settings.devicePort = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Upload Path").setDesc(
      "The directory on the device where notes will be saved (default is /)."
    ).addText(
      (text) => text.setPlaceholder("/").setValue(this.plugin.settings.uploadPath).onChange(async (value) => {
        this.plugin.settings.uploadPath = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Auto-create missing directory").setDesc("Automatically create the upload directory on the device if it doesn't exist.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoCreateDir).onChange(async (value) => {
        this.plugin.settings.autoCreateDir = value;
        await this.plugin.saveSettings();
      })
    );
  }
};
